# php.iniに記載する内容は変更するパラメータのみで良い。
upload_max_filesize = 100M
post_max_size = 120M
memory_limit = 128M
sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025"
max_input_vars = 2000
[Date]
date.timezone = "Asia/Tokyo"