# ★重要VirtualHostを設定する場合は、 ローカルPCのhostsファイルを編集する必要あり。
# 127.0.0.1       locallaravel
<VirtualHost *:80>
	ServerName locallaravel
	ServerAdmin webmaster@locallaravel
	# Laravelプロジェクト名毎にtask_testの部分を変更する
	# DocumentRoot /var/www/html/public
	DocumentRoot /var/www/html/src/public
	# <Directory /var/www/html/public>
	<Directory /var/www/html/src/public>
		# (CGI,SSIが動くようにExecCGI Includesを追加）
		Options ExecCGI Indexes FollowSymLinks MultiViews Includes
		AllowOverride All
		Order allow,deny
		allow from all
		# サーバー情報を表示しないようにする
		ServerSignature Off
		# *.cgiとPerlのCGIを動かす
		AddHandler cgi-script .cgi .pl
		# rubyのcgiや.shtmlも動かす
		AddType text/html .rhtml .shtml
	</Directory>
                                
</VirtualHost>
